import 'package:flutter_test/flutter_test.dart';
import 'package:speakup/review/turn_feedback.dart';
import 'package:speakup/review/turn_feedback_decoder.dart';

import 'turn_feedback_fixture.dart';

void main() {
  test('decodes every canonical SpeechFeedback state', () {
    final contract = speechFeedbackContractFixture();

    expect(
      decodeSpeechFeedback(contract['queued']).feedbackStatus,
      SpeechFeedbackStatus.queued,
    );
    expect(
      decodeSpeechFeedback(contract['running']).source,
      isA<AgentVoiceMessageFeedbackSource>(),
    );
    final provisional = decodeSpeechFeedback(contract['ready_provisional']);
    expect(provisional.strategyRef, 'qianwen-speech-feedback/v1');
    expect(provisional.pipelineVersion, 'speech-feedback-pipeline/v1');
    expect(
      provisional.scoreabilityStatus,
      SpeechFeedbackScoreabilityStatus.provisional,
    );
    expect(provisional.items, hasLength(1));
    expect(
      provisional.items.single.repracticeMode,
      SpeechFeedbackRepracticeMode.sameQuestion,
    );
    final insufficient = decodeSpeechFeedback(contract['ready_insufficient']);
    expect(
      insufficient.scoreabilityStatus,
      SpeechFeedbackScoreabilityStatus.insufficient,
    );
    expect(insufficient.items, isEmpty);
    final failed = decodeSpeechFeedback(contract['failed']);
    expect(failed.feedbackStatus, SpeechFeedbackStatus.failed);
    expect(failed.stableFailure?.retryable, isTrue);
  });

  test('rejects unknown fields including every numeric scoring shape', () {
    final contract = speechFeedbackContractFixture();
    final rootScore = cloneSpeechFeedbackFixture(contract['ready_provisional'])
      ..['score'] = 90;
    final itemScore = cloneSpeechFeedbackFixture(contract['ready_provisional']);
    _firstItem(itemScore)['display_score'] = 4;
    final acousticGuess = cloneSpeechFeedbackFixture(
      contract['ready_provisional'],
    );
    (acousticGuess['acoustic_assessment']!
            as Map<String, Object?>)['pronunciation_score'] =
        80;

    for (final value in [rootScore, itemScore, acousticGuess]) {
      expect(
        () => decodeSpeechFeedback(value),
        throwsA(isA<SpeechFeedbackDecodeException>()),
      );
    }
  });

  test('rejects feedback generated by a different frozen pipeline', () {
    final wrongStrategy = cloneSpeechFeedbackFixture(
      speechFeedbackContractFixture()['ready_provisional'],
    )..['strategy_ref'] = 'other-speech-feedback/v1';
    final wrongPipeline = cloneSpeechFeedbackFixture(
      speechFeedbackContractFixture()['ready_provisional'],
    )..['pipeline_version'] = 'speech-feedback-pipeline-v2';

    for (final value in [wrongStrategy, wrongPipeline]) {
      expect(
        () => decodeSpeechFeedback(value),
        throwsA(isA<SpeechFeedbackDecodeException>()),
      );
    }
  });

  test('enforces the exact status-specific payload shapes', () {
    final contract = speechFeedbackContractFixture();
    final queuedWithScoreability = cloneSpeechFeedbackFixture(
      contract['queued'],
    )..['scoreability_status'] = 'PROVISIONAL';
    final provisionalWithoutItems = cloneSpeechFeedbackFixture(
      contract['ready_provisional'],
    )..['items'] = <Object?>[];
    final insufficientWithoutReasons = cloneSpeechFeedbackFixture(
      contract['ready_insufficient'],
    )..remove('reason_codes');
    final failedWithoutCompletedAt = cloneSpeechFeedbackFixture(
      contract['failed'],
    )..remove('completed_at');

    for (final value in [
      queuedWithScoreability,
      provisionalWithoutItems,
      insufficientWithoutReasons,
      failedWithoutCompletedAt,
    ]) {
      expect(
        () => decodeSpeechFeedback(value),
        throwsA(isA<SpeechFeedbackDecodeException>()),
      );
    }
  });

  test('binds item anchors and repractice mode to the strong source type', () {
    final contract = speechFeedbackContractFixture();
    final wrongTurn = cloneSpeechFeedbackFixture(contract['ready_provisional']);
    _firstAnchor(wrongTurn)['turn_id'] = 'turn_other';
    final wrongMode = cloneSpeechFeedbackFixture(contract['ready_provisional']);
    _firstItem(wrongMode)['repractice_mode'] = 'SAME_THREAD';
    final mixedAnchor = cloneSpeechFeedbackFixture(
      contract['ready_provisional'],
    );
    _firstItem(mixedAnchor)['anchor'] = <String, Object?>{
      'anchor_kind': 'AGENT_TRANSCRIPT',
      'transcript_evidence_id': 'evidence_agent_001',
      'message_id': 'message_agent_001',
      'start_utf8_byte': 0,
      'end_utf8_byte': 8,
      'original_excerpt': 'I manage',
    };

    for (final value in [wrongTurn, wrongMode, mixedAnchor]) {
      expect(
        () => decodeSpeechFeedback(value),
        throwsA(isA<SpeechFeedbackDecodeException>()),
      );
    }
  });

  test('accepts SAME_THREAD only for a matching Agent transcript anchor', () {
    final value = cloneSpeechFeedbackFixture(
      speechFeedbackContractFixture()['ready_provisional'],
    );
    value['source'] = <String, Object?>{
      'source_kind': 'AGENT_VOICE_MESSAGE',
      'thread_id': 'thread_agent_001',
      'message_id': 'message_agent_001',
      'transcript_evidence_id': 'evidence_agent_001',
      'candidate_version': 2,
    };
    _firstItem(value)
      ..['repractice_mode'] = 'SAME_THREAD'
      ..['anchor'] = <String, Object?>{
        'anchor_kind': 'AGENT_TRANSCRIPT',
        'transcript_evidence_id': 'evidence_agent_001',
        'message_id': 'message_agent_001',
        'start_utf8_byte': 0,
        'end_utf8_byte': 8,
        'original_excerpt': 'I manage',
      };

    final decoded = decodeSpeechFeedback(value);

    expect(decoded.source, isA<AgentVoiceMessageFeedbackSource>());
    expect(
      decoded.items.single.repracticeMode,
      SpeechFeedbackRepracticeMode.sameThread,
    );
  });

  test('validates exact UTF-8 anchor lengths without guessing source text', () {
    final valid = cloneSpeechFeedbackFixture(
      speechFeedbackContractFixture()['ready_provisional'],
    );
    _firstAnchor(valid)
      ..['start_utf8_byte'] = 4
      ..['end_utf8_byte'] = 10
      ..['original_excerpt'] = '你好';
    final broken = cloneSpeechFeedbackFixture(valid);
    _firstAnchor(broken)['end_utf8_byte'] = 9;

    expect(
      decodeSpeechFeedback(valid).items.single.anchor.originalExcerpt,
      '你好',
    );
    expect(
      () => decodeSpeechFeedback(broken),
      throwsA(isA<SpeechFeedbackDecodeException>()),
    );
  });

  test('rejects guessed acoustics and forbidden transcript controls', () {
    final contract = speechFeedbackContractFixture();
    final acoustic = cloneSpeechFeedbackFixture(contract['ready_provisional']);
    (acoustic['acoustic_assessment']!
            as Map<String, Object?>)['pronunciation'] =
        'ASSESSED';
    final control = cloneSpeechFeedbackFixture(contract['ready_provisional']);
    _firstAnchor(control)
      ..['end_utf8_byte'] = 3
      ..['original_excerpt'] = 'a\u0001b';
    final c1Control = cloneSpeechFeedbackFixture(contract['ready_provisional']);
    _firstAnchor(c1Control)
      ..['end_utf8_byte'] = 4
      ..['original_excerpt'] = 'a\u0085b';
    final oversizedFeedback = cloneSpeechFeedbackFixture(
      contract['ready_provisional'],
    );
    _firstItem(oversizedFeedback)['explanation'] = '你' * 683;

    for (final value in [acoustic, control, c1Control, oversizedFeedback]) {
      expect(
        () => decodeSpeechFeedback(value),
        throwsA(isA<SpeechFeedbackDecodeException>()),
      );
    }
  });

  test('validates opaque status URLs without accepting navigation syntax', () {
    expect(
      validSpeechFeedbackStatusUrl(
        '/v1/speech-feedback/30000000-0000-4000-8000-000000000001',
      ),
      isTrue,
    );
    expect(
      validSpeechFeedbackStatusUrl('/v1/speech-feedback/opaque_id.001~a'),
      isTrue,
    );
    for (final value in [
      'https://other.test/v1/speech-feedback/opaque_id',
      '/v1/speech-feedback/opaque_id?token=secret',
      '/v1/speech-feedback/opaque_id#fragment',
      '/v1/speech-feedback/%2e%2e',
      '/v1/speech-feedback/..',
    ]) {
      expect(validSpeechFeedbackStatusUrl(value), isFalse, reason: value);
    }
  });
}

Map<String, Object?> _firstItem(Map<String, Object?> value) {
  return (value['items']! as List<Object?>).first as Map<String, Object?>;
}

Map<String, Object?> _firstAnchor(Map<String, Object?> value) {
  return _firstItem(value)['anchor']! as Map<String, Object?>;
}
